/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Java_Escritorio_2;


import java.text.Normalizer;
import java.util.StringTokenizer;
import Secundarios.AlertInformation;
import Secundarios.Insertar;
import Secundarios.Remplazar;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.DataFlavor;
import java.awt.datatransfer.StringSelection;
import java.awt.datatransfer.UnsupportedFlavorException;
import java.io.IOException;


/**
 *
 * @author Oseas Xt
 */
public class Cadenas_Murcielagos extends javax.swing.JFrame {
    public static boolean creoNuevo = false;
    public static boolean abrioArchivo = false;
    public static String valor;
    /**
     * Creates new form Cadenas_Murcielagos
     */
    public Cadenas_Murcielagos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbltitulo1 = new javax.swing.JLabel();
        lblanuncio1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txta_pantalla1 = new javax.swing.JTextArea();
        btn_procesar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbl_longitud_texto = new javax.swing.JLabel();
        lbl_total_palabras = new javax.swing.JLabel();
        lbl_primer_letra_texto = new javax.swing.JLabel();
        lbl_ultima_letra_texto = new javax.swing.JLabel();
        lbl_letra_central_texto = new javax.swing.JLabel();
        lbl_primera_palabra = new javax.swing.JLabel();
        lbl_palabra_central = new javax.swing.JLabel();
        lbl_ultima_palabra = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lbl_rep_A = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lbl_rep_E = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        lbl_rep_I = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        lbl_rep_O = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        lbl_rep_U = new javax.swing.JLabel();
        lbl_cant_par = new javax.swing.JLabel();
        lbl_cant_impar = new javax.swing.JLabel();
        lbltitulo2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txta_pantalla2 = new javax.swing.JTextArea();
        lbl_nombre = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbltitulo1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        lbltitulo1.setText("MANEJO DE CADENAS");

        lblanuncio1.setText("Ingrese un texto o un archivo.");

        txta_pantalla1.setColumns(20);
        txta_pantalla1.setRows(5);
        jScrollPane1.setViewportView(txta_pantalla1);

        btn_procesar.setText("PROCESAR");
        btn_procesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_procesarActionPerformed(evt);
            }
        });

        jLabel1.setText("Longitud de texto:");

        jLabel2.setText("Total de palabras:");

        jLabel3.setText("Primer letra del texto:");

        jLabel4.setText("Última letra del texto:");

        jLabel5.setText("Letra central del texto:");

        jLabel6.setText("Primera palabra:");

        jLabel7.setText("Palabra central:");

        jLabel8.setText("Última palabra:");

        lbl_longitud_texto.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lbl_longitud_texto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_longitud_texto.setText("-");

        lbl_total_palabras.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lbl_total_palabras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_total_palabras.setText("-");

        lbl_primer_letra_texto.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lbl_primer_letra_texto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_primer_letra_texto.setText("-");

        lbl_ultima_letra_texto.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lbl_ultima_letra_texto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_ultima_letra_texto.setText("-");

        lbl_letra_central_texto.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lbl_letra_central_texto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_letra_central_texto.setText("-");

        lbl_primera_palabra.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lbl_primera_palabra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_primera_palabra.setText("-");

        lbl_palabra_central.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lbl_palabra_central.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_palabra_central.setText("-");

        lbl_ultima_palabra.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lbl_ultima_palabra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_ultima_palabra.setText("-");

        jLabel17.setText("Repeticiones de \"A\",\"a\" ó \"á\".");

        lbl_rep_A.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lbl_rep_A.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_rep_A.setText("-");

        jLabel19.setText("Repeticiones de \"E\",\"e\" ó \"é\".");

        lbl_rep_E.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lbl_rep_E.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_rep_E.setText("-");

        jLabel21.setText("Repeticiones de \"I\",\"i\" ó \"í\".");

        lbl_rep_I.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lbl_rep_I.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_rep_I.setText("-");

        jLabel23.setText("Repeticiones de \"O\",\"o\" ó \"ó\".");

        lbl_rep_O.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lbl_rep_O.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_rep_O.setText("-");

        jLabel25.setText("Repeticiones de \"U\",\"u\" ó \"ú\".");

        jLabel26.setText("Palabras con cantidad de caracterres par:");

        jLabel27.setText("Palabras con cantidad de caracteres impar:");

        lbl_rep_U.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lbl_rep_U.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_rep_U.setText("-");

        lbl_cant_par.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lbl_cant_par.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_cant_par.setText("-");

        lbl_cant_impar.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lbl_cant_impar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_cant_impar.setText("-");

        lbltitulo2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        lbltitulo2.setText("TRADUCCIÓN A CLAVE MURCIELAGO");

        txta_pantalla2.setColumns(20);
        txta_pantalla2.setRows(5);
        jScrollPane2.setViewportView(txta_pantalla2);

        lbl_nombre.setForeground(new java.awt.Color(204, 204, 204));

        jMenu1.setText("Archivo");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setText("Abrir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem2.setText("Guardar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F12, 0));
        jMenuItem3.setText("Guardar como");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Editar");

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem4.setText("Copiar");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem5.setText("Cortar");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem6.setText("Pegar");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem7.setText("Buscar");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem8.setText("Reemplazar");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbltitulo2)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(lbl_longitud_texto, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lbl_total_palabras, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lbl_primer_letra_texto, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lbl_ultima_letra_texto, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(lbl_letra_central_texto, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lbl_primera_palabra, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lbl_palabra_central, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lbl_ultima_palabra, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(lbl_rep_A, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lbl_rep_E, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lbl_rep_I, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lbl_rep_O, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(lbl_rep_U, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lbl_cant_par, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lbl_cant_impar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblanuncio1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbl_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(216, 216, 216)
                                .addComponent(lbltitulo1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(243, 243, 243)
                                .addComponent(btn_procesar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbltitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblanuncio1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_procesar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel4))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl_longitud_texto)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbl_total_palabras)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbl_primer_letra_texto)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbl_ultima_letra_texto)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel8))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl_letra_central_texto)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbl_primera_palabra)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbl_palabra_central)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbl_ultima_palabra))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel21)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel23))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl_rep_A)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbl_rep_E)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbl_rep_I)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbl_rep_O)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel25)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel26)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel27))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl_rep_U)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbl_cant_par)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbl_cant_impar)))))
                        .addGap(18, 18, 18)
                        .addComponent(lbltitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_procesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_procesarActionPerformed

        String texto = txta_pantalla1.getText();
        String letraU = texto.substring(texto.length()-1);
        String[] palabraarray = txta_pantalla1.getText().split(" ");
        String[] chararray = texto.split("");
        int longitud = 0;
        
         for (int i = 0; i < palabraarray.length; i++){
            longitud ++;

        }
        
        StringTokenizer st = new StringTokenizer(texto);
        lbl_total_palabras.setText(""+st.countTokens());

        StringTokenizer tokens = new StringTokenizer(texto);
        String Palabra1 = tokens.nextToken();
        lbl_primera_palabra.setText(Palabra1);
     
        char primerletra = texto.charAt(0);
        lbl_primer_letra_texto.setText(""+primerletra);

        int stringLength = texto.length();
        lbl_longitud_texto.setText(""+stringLength);

        char [] ultimaletra = letraU.toCharArray();
        lbl_ultima_letra_texto.setText(""+ultimaletra[ultimaletra.length -1]);

        String strLastToken = null;
        while( st.hasMoreTokens() ) {
            strLastToken = st.nextToken();
        }
        lbl_ultima_palabra.setText("" + strLastToken);

        int letracentral = stringLength/2;
        lbl_letra_central_texto.setText(chararray[letracentral]);

        int palabracentral = longitud/2;
        lbl_palabra_central.setText(palabraarray[palabracentral]);

        String[] valorarray = texto.split(" ");
        int Par=0;
        int Impar=0;
        for (String parimpar : valorarray) {
            int contar = parimpar.length();
            if (contar % 2 == 0 ){
                Par = Par + 1;
            }else {
                Impar = Impar + 1;
            }
        }
        lbl_cant_par.setText(Integer.toString(Par));
        lbl_cant_impar.setText(Integer.toString(Impar));

        int contadorA=0;
        int contadorE=0;
        int contadorI=0;
        int contadorO=0;
        int contadorU=0;

        for (int f = 0 ; f < texto.length(); f++){
            if (texto.charAt(f)== 'E' || texto.charAt(f)== 'e' || texto.charAt(f)== 'É' || texto.charAt(f)== 'é'){
                contadorE++;
            }
        }
        lbl_rep_E.setText(""+contadorE);

        for (int l = 0 ; l < texto.length(); l++){
            if (texto.charAt(l)== 'A' || texto.charAt(l)== 'a' || texto.charAt(l)== 'Á' || texto.charAt(l)== 'á'){
                contadorA++;
            }
        }
        lbl_rep_A.setText(""+contadorA);

        for (int k = 0 ; k < texto.length(); k++){
            if (texto.charAt(k)== 'O' || texto.charAt(k)== 'o' || texto.charAt(k)== 'Ó' || texto.charAt(k)== 'ó'){
                contadorO++;
            }
        }
        lbl_rep_O.setText(""+contadorO);

        for (int j = 0 ; j < texto.length(); j++){
            if (texto.charAt(j)== 'U' || texto.charAt(j)== 'u' || texto.charAt(j)== 'Ú' || texto.charAt(j)== 'ú'){
                contadorU++;
            }
        }
        lbl_rep_U.setText(""+contadorU);

        for (int i = 0 ; i < texto.length(); i++){
            if (texto.charAt(i)== 'I' || texto.charAt(i)== 'i' || texto.charAt(i)== 'Í' || texto.charAt(i)== 'í'){
                contadorI++;
            }
        }
        lbl_rep_I.setText(""+contadorI);

        String cadenaMurcielago = Normalizer.normalize(texto, Normalizer.Form.NFD);
        String Cadena2 = cadenaMurcielago.replaceAll("[^\\p{ASCII}]", "");
        String s= Cadena2.toLowerCase();

        String normal="a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z";
        String murcielago="7,B,3,D,5,F,8,H,4,J,K,6,0,N,9,P,Q,2,S,T,1,V,W,X,Y,Z";
        String[] abecedario = normal.split(",");
        String[] traductor= murcielago.split(",");

        for (String abecedario1 : abecedario) {
            System.out.println(abecedario1);
        }
        for (String traductor1 : traductor) {
            System.out.println(traductor1);
        }
        for (int i = 0; i <26; i++){
            s = s.replace(abecedario[i], traductor[i]);
        }
        txta_pantalla2.setText(s);
       
    }//GEN-LAST:event_btn_procesarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
         new file().LeerFichero(this);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
                if (abrioArchivo) {
            System.out.println("Existente");
            new file().GuardarFichero(Cadenas_Murcielagos.txta_pantalla1.getText(), Cadenas_Murcielagos.lbl_nombre.getText());
        }
        if (creoNuevo) {
            System.out.println("Nuevo");
            new file().CrearFicheroNuevo(this, Cadenas_Murcielagos.txta_pantalla1.getText(), Cadenas_Murcielagos.lbl_nombre.getText());
        }
        if (!creoNuevo && !abrioArchivo) {
            Secundarios.AlertInformation a = new AlertInformation(this, true);
            AlertInformation.lbl_mensaje1.setText("Debes crear o abrir un archvo");
            AlertInformation.lbl_mensaje2.setText("para poder guardarlo.");
            a.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        System.out.println("Existente");
            new file().GuardarFichero(Cadenas_Murcielagos.txta_pantalla1.getText(), Cadenas_Murcielagos.lbl_nombre.getText());
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
           StringSelection selection = new StringSelection(txta_pantalla1.getText());
        Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
        clipboard.setContents(selection, selection);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        StringSelection selection = new StringSelection(txta_pantalla1.getText());
        Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
        clipboard.setContents(selection, selection);  
        txta_pantalla1.setText("");
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
    DataFlavor flavor = DataFlavor.stringFlavor;
    if (clipboard.isDataFlavorAvailable(flavor)) {
      try {
        String text = (String) clipboard.getData(flavor);
        txta_pantalla1.setText(text);
      } catch (UnsupportedFlavorException | IOException e) {
        System.out.println(e);
      }
    }
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        Secundarios.Insertar a = new Insertar(this, true);
        a.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        Secundarios.Remplazar a = new Remplazar(this, true);
        a.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadenas_Murcielagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadenas_Murcielagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadenas_Murcielagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadenas_Murcielagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Cadenas_Murcielagos().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_procesar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JLabel lbl_cant_impar;
    public static javax.swing.JLabel lbl_cant_par;
    public static javax.swing.JLabel lbl_letra_central_texto;
    public static javax.swing.JLabel lbl_longitud_texto;
    public static javax.swing.JLabel lbl_nombre;
    public static javax.swing.JLabel lbl_palabra_central;
    public static javax.swing.JLabel lbl_primer_letra_texto;
    public static javax.swing.JLabel lbl_primera_palabra;
    public static javax.swing.JLabel lbl_rep_A;
    public static javax.swing.JLabel lbl_rep_E;
    public static javax.swing.JLabel lbl_rep_I;
    public static javax.swing.JLabel lbl_rep_O;
    public static javax.swing.JLabel lbl_rep_U;
    public static javax.swing.JLabel lbl_total_palabras;
    public static javax.swing.JLabel lbl_ultima_letra_texto;
    public static javax.swing.JLabel lbl_ultima_palabra;
    private javax.swing.JLabel lblanuncio1;
    private javax.swing.JLabel lbltitulo1;
    private javax.swing.JLabel lbltitulo2;
    public static javax.swing.JTextArea txta_pantalla1;
    private javax.swing.JTextArea txta_pantalla2;
    // End of variables declaration//GEN-END:variables
}
